author: Shiraz McClennon
title: Shiraz McClennon
description: UK A-level student, invested in digital privacy and cybersecurity
logo: assets/images/smcclennon.png
lang: en_GB
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

social:
  name: Shiraz McClennon
  links:
    - https://github.com/smcclennon
google_analytics:
theme: jekyll-theme-cayman
url: "https://smcclennon.github.io"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - scope:
      path: "/projects/*"
    values:
      sitemap: false
  - scope:
      path: "update/*"
    values:
      sitemap: false
  - scope:
      path: "404.html"
    values:
      sitemap: false

  - scope:
      path: "update/api/index.html"
    values:
      sitemap: true
