author: Shiraz McClennon
title: Shiraz McClennon
description: Computer science student interested in cyber security
url: "https://smcclennon.github.io"
logo: assets/images/smcclennon.png
lang: en_EU
social:
  name: Shiraz McClennon
  links:
    - https://github.com/smcclennon
show_downloads: true
google_analytics: UA-151447933-1
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag