name: Lint Commit Messages

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
